<a href="https://colab.research.google.com/github/OmegaS48/Internship_NITP/blob/main/Intern_Day4_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import sklearn.preprocessing as StandardScaler

In [ ]:
d=pd.read_csv('Train_ULAK.csv')

/tmp/ipykernel_1768/3582016830.py:1: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  d=pd.read_csv('Train_ULAK.csv')

In [ ]:
d.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80.0,68855579,10.0,6,1038,11595,346,0,103.800000,167.133879,...,32.0,998.0,0.0,998.0,998.0,68300000.0,0.0,68300000.0,68300000.0,DoS Hulk
1,53.0,196,2.0,2,70,174,35,35,35.000000,0.000000,...,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,123.0,118,2.0,2,96,96,48,48,48.000000,0.000000,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,80.0,295657,7.0,10,1114,15841,1084,0,159.142857,407.829796,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,80.0,15705351,7.0,5,407,452,377,0,58.142857,140.620563,...,20.0,360718.0,0.0,360718.0,360718.0,9767208.0,0.0,9767208.0,9767208.0,BENIGN

In [ ]:
d.shape

(730870, 79)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder=LabelEncoder()

In [ ]:
d.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,68855579,10.0,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000.0,2.0,602465.0,1.204930e+05,1.934046e+05,444104.0,49.0,0.0,0.0,0.0,0.0,328.0,200.0,0.145232,0.087139,0.0,4344.0,743.117647,1341.078106,1.798490e+06,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,789.562500,103.800000,1932.5,328.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,1038.0,6.0,11595.0,251.0,235.0,3.0,32.0,998.0,0.0,998.0,998.0,68300000.0,0.0,68300000.0,68300000.0,4
1,196,2.0,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3.0,3.0,3.0,3.000000e+00,0.000000e+00,3.0,3.0,0.0,0.0,0.0,0.0,64.0,64.0,10204.081630,10204.081630,35.0,87.0,55.800000,28.481573,8.112000e+02,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,69.750000,35.000000,87.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,70.0,2.0,174.0,-1.0,-1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,118,2.0,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3.0,3.0,4.0,4.000000e+00,0.000000e+00,4.0,4.0,0.0,0.0,0.0,0.0,40.0,40.0,16949.152540,16949.152540,48.0,48.0,48.000000,0.000000,0.000000e+00,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,60.000000,48.000000,48.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,96.0,2.0,96.0,-1.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,295657,7.0,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299.0,192.0,262576.0,2.917511e+04,8.701429e+04,261213.0,2.0,0.0,0.0,0.0,0.0,152.0,208.0,23.676084,33.822977,0.0,2920.0,941.944444,968.551646,9.380923e+05,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,997.352941,159.142857,1584.1,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1114.0,10.0,15841.0,8192.0,11.0,6.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,15705351,7.0,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208.0,375.0,10100000.0,2.532037e+06,4.846203e+06,9799947.0,1261.0,0.0,0.0,0.0,0.0,152.0,108.0,0.445708,0.318363,0.0,377.0,66.076923,123.295351,1.520174e+04,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,71.583333,58.142857,90.4,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,407.0,5.0,452.0,8192.0,16384.0,6.0,20.0,360718.0,0.0,360718.0,360718.0,9767208.0,0.0,9767208.0,9767208.0,0

In [ ]:
d.isnull().sum()

 Destination Port              1
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      2
 Idle Std                      2
 Idle Max                      2
 Idle Min                      2
 Label                         2
Length: 79, dtype: int64

In [ ]:
pd.set_option('display.max_columns',None)

In [ ]:
a=d[' Label']

In [ ]:
d[' Label']=labelencoder.fit_transform(d[' Label'])

In [ ]:
d.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80.0,68855579,10.0,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000.0,2.0,602465.0,1.204930e+05,1.934046e+05,444104.0,49.0,0.0,0.0,0.0,0.0,328.0,200.0,0.145232,0.087139,0.0,4344.0,743.117647,1341.078106,1.798490e+06,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,789.562500,103.800000,1932.5,328.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,1038.0,6.0,11595.0,251.0,235.0,3.0,32.0,998.0,0.0,998.0,998.0,68300000.0,0.0,68300000.0,68300000.0,4
1,53.0,196,2.0,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3.0,3.0,3.0,3.000000e+00,0.000000e+00,3.0,3.0,0.0,0.0,0.0,0.0,64.0,64.0,10204.081630,10204.081630,35.0,87.0,55.800000,28.481573,8.112000e+02,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,69.750000,35.000000,87.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,70.0,2.0,174.0,-1.0,-1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,123.0,118,2.0,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3.0,3.0,4.0,4.000000e+00,0.000000e+00,4.0,4.0,0.0,0.0,0.0,0.0,40.0,40.0,16949.152540,16949.152540,48.0,48.0,48.000000,0.000000,0.000000e+00,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,60.000000,48.000000,48.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,96.0,2.0,96.0,-1.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,80.0,295657,7.0,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299.0,192.0,262576.0,2.917511e+04,8.701429e+04,261213.0,2.0,0.0,0.0,0.0,0.0,152.0,208.0,23.676084,33.822977,0.0,2920.0,941.944444,968.551646,9.380923e+05,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,997.352941,159.142857,1584.1,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1114.0,10.0,15841.0,8192.0,11.0,6.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,80.0,15705351,7.0,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208.0,375.0,10100000.0,2.532037e+06,4.846203e+06,9799947.0,1261.0,0.0,0.0,0.0,0.0,152.0,108.0,0.445708,0.318363,0.0,377.0,66.076923,123.295351,1.520174e+04,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,71.583333,58.142857,90.4,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,407.0,5.0,452.0,8192.0,16384.0,6.0,20.0,360718.0,0.0,360718.0,360718.0,9767208.0,0.0,9767208.0,9767208.0,0

In [ ]:
d[' Label'].value_counts()

 Label
0     587120
4      59333
10     41187
2      32994
3       2662
7       2009
11      1574
6       1501
5       1412
1        492
12       389
14       179
9          9
13         6
15         2
8          1
Name: count, dtype: int64

In [ ]:
d.drop(columns=[' Destination Port'],inplace=True)

In [ ]:
d.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,68855579,10.0,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000.0,2.0,602465.0,1.204930e+05,1.934046e+05,444104.0,49.0,0.0,0.0,0.0,0.0,328.0,200.0,0.145232,0.087139,0.0,4344.0,743.117647,1341.078106,1.798490e+06,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,789.562500,103.800000,1932.5,328.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,1038.0,6.0,11595.0,251.0,235.0,3.0,32.0,998.0,0.0,998.0,998.0,68300000.0,0.0,68300000.0,68300000.0,4
1,196,2.0,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3.0,3.0,3.0,3.000000e+00,0.000000e+00,3.0,3.0,0.0,0.0,0.0,0.0,64.0,64.0,10204.081630,10204.081630,35.0,87.0,55.800000,28.481573,8.112000e+02,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,69.750000,35.000000,87.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,70.0,2.0,174.0,-1.0,-1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,118,2.0,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3.0,3.0,4.0,4.000000e+00,0.000000e+00,4.0,4.0,0.0,0.0,0.0,0.0,40.0,40.0,16949.152540,16949.152540,48.0,48.0,48.000000,0.000000,0.000000e+00,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,60.000000,48.000000,48.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,96.0,2.0,96.0,-1.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,295657,7.0,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299.0,192.0,262576.0,2.917511e+04,8.701429e+04,261213.0,2.0,0.0,0.0,0.0,0.0,152.0,208.0,23.676084,33.822977,0.0,2920.0,941.944444,968.551646,9.380923e+05,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,997.352941,159.142857,1584.1,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1114.0,10.0,15841.0,8192.0,11.0,6.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,15705351,7.0,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208.0,375.0,10100000.0,2.532037e+06,4.846203e+06,9799947.0,1261.0,0.0,0.0,0.0,0.0,152.0,108.0,0.445708,0.318363,0.0,377.0,66.076923,123.295351,1.520174e+04,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,71.583333,58.142857,90.4,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,407.0,5.0,452.0,8192.0,16384.0,6.0,20.0,360718.0,0.0,360718.0,360718.0,9767208.0,0.0,9767208.0,9767208.0,0

In [ ]:
X=d.drop(columns=[' Label'])

In [ ]:
Y=d[' Label']

In [ ]:
X.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,68855579,10.0,6,1038,11595,346,0,103.800000,167.133879,4344,0,1932.5,1754.831473,1.834710e+02,0.232370,4.590372e+06,1.760000e+07,68300000,2,68700000,7633007.889,2.270000e+07,68300000.0,2.0,602465.0,1.204930e+05,1.934046e+05,444104.0,49.0,0.0,0.0,0.0,0.0,328.0,200.0,0.145232,0.087139,0.0,4344.0,743.117647,1341.078106,1.798490e+06,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,789.562500,103.800000,1932.5,328.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,1038.0,6.0,11595.0,251.0,235.0,3.0,32.0,998.0,0.0,998.0,998.0,68300000.0,0.0,68300000.0,68300000.0
1,196,2.0,2,70,174,35,35,35.000000,0.000000,87,87,87.0,0.000000,1.244898e+06,20408.163270,6.533333e+01,1.079645e+02,190,3,3,3.000,0.000000e+00,3.0,3.0,3.0,3.000000e+00,0.000000e+00,3.0,3.0,0.0,0.0,0.0,0.0,64.0,64.0,10204.081630,10204.081630,35.0,87.0,55.800000,28.481573,8.112000e+02,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,69.750000,35.000000,87.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,70.0,2.0,174.0,-1.0,-1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,118,2.0,2,96,96,48,48,48.000000,0.000000,48,48,48.0,0.000000,1.627119e+06,33898.305080,3.933333e+01,6.206717e+01,111,3,3,3.000,0.000000e+00,3.0,3.0,4.0,4.000000e+00,0.000000e+00,4.0,4.0,0.0,0.0,0.0,0.0,40.0,40.0,16949.152540,16949.152540,48.0,48.0,48.000000,0.000000,0.000000e+00,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,60.000000,48.000000,48.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,96.0,2.0,96.0,-1.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,295657,7.0,10,1114,15841,1084,0,159.142857,407.829796,2920,0,1584.1,792.273304,5.734686e+04,57.499061,1.847856e+04,5.298594e+04,209299,1,295464,49244.000,8.134591e+04,209299.0,192.0,262576.0,2.917511e+04,8.701429e+04,261213.0,2.0,0.0,0.0,0.0,0.0,152.0,208.0,23.676084,33.822977,0.0,2920.0,941.944444,968.551646,9.380923e+05,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,997.352941,159.142857,1584.1,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1114.0,10.0,15841.0,8192.0,11.0,6.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,15705351,7.0,5,407,452,377,0,58.142857,140.620563,220,0,90.4,118.333427,5.469473e+01,0.764071,1.427759e+06,3.221493e+06,9767208,82,15700000,2617558.500,4.134537e+06,9767208.0,375.0,10100000.0,2.532037e+06,4.846203e+06,9799947.0,1261.0,0.0,0.0,0.0,0.0,152.0,108.0,0.445708,0.318363,0.0,377.0,66.076923,123.295351,1.520174e+04,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,71.583333,58.142857,90.4,152.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,407.0,5.0,452.0,8192.0,16384.0,6.0,20.0,360718.0,0.0,360718.0,360718.0,9767208.0,0.0,9767208.0,9767208.0

In [ ]:
Y.head()

0    4
1    0
2    0
3    0
4    0
Name:  Label, dtype: int64

In [ ]:
X.isnull().sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
                               ..
 Active Min                     2
Idle Mean                       2
 Idle Std                       2
 Idle Max                       2
 Idle Min                       2
Length: 77, dtype: int64

In [ ]:
X['Flow Bytes/s'].fillna(X['Flow Bytes/s'].median(),inplace=True)

/tmp/ipykernel_1768/1662676317.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['Flow Bytes/s'].fillna(X['Flow Bytes/s'].median(),inplace=True)

In [ ]:
X.isnull().sum()

 Flow Duration                  0
 Total Fwd Packets              0
 Total Backward Packets         0
Total Length of Fwd Packets     0
 Total Length of Bwd Packets    0
                               ..
 Active Min                     2
Idle Mean                       2
 Idle Std                       2
 Idle Max                       2
 Idle Min                       2
Length: 77, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
X_train.replace([np.inf, -np.inf], 0, inplace=True)

In [ ]:
X_test.replace([np.inf,-np.inf],0,inplace=True)

In [ ]:
X_train.head()

,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
501712,1,2.0,0,12,0,6,6,6.0,0.00000,0,0,0.0,0.0,1.200000e+07,2.000000e+06,1.00000,0.000000,1,1,1,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,0.0,2.000000e+06,0.000000,6.0,6.0,6.000000,0.000000,0.000000,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9.00,6.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,12.0,0.0,0.0,6286.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86656,49595,2.0,2,68,428,34,34,34.0,0.00000,214,214,214.0,0.0,1.000101e+04,8.065329e+01,16531.66667,28588.661740,49543,4,4,4.0,0.0,4.0,4.0,48.0,48.0,0.0,48.0,48.0,0.0,0.0,0.0,0.0,40.0,40.0,4.032665e+01,40.326646,34.0,214.0,106.000000,98.590060,9720.000000,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,132.50,34.0,214.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,68.0,2.0,428.0,-1.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86812,186,2.0,2,90,196,45,45,45.0,0.00000,98,98,98.0,0.0,1.537634e+06,2.150538e+04,62.00000,105.655099,184,1,1,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,64.0,64.0,1.075269e+04,10752.688170,45.0,98.0,66.200000,29.029296,842.700000,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,82.75,45.0,98.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,90.0,2.0,196.0,-1.0,-1.0,1.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
660397,3,2.0,0,37,0,31,6,18.5,17.67767,0,0,0.0,0.0,1.233333e+07,6.666667e+05,3.00000,0.000000,3,3,3,3.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,40.0,0.0,6.666667e+05,0.000000,6.0,31.0,22.666667,14.433757,208.333333,0.0,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,34.00,18.5,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,37.0,0.0,0.0,110.0,-1.0,1.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
450137,30419,1.0,1,55,183,55,55,55.0,0.00000,183,183,183.0,0.0,7.824057e+03,6.574838e+01,30419.00000,0.000000,30419,30419,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,3.287419e+01,32.874190,55.0,183.0,97.666667,73.900834,5461.333333,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,146.50,55.0,183.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,55.0,1.0,183.0,-1.0,-1.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
X_train.isin().any()

AttributeError: 'numpy.ndarray' object has no attribute 'isin'

In [ ]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

ValueError: could not convert string to float: 'DoS Hulk'

In [ ]:
X_train

In [ ]:
Y_train.head()

In [ ]:
Y_train.head()

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb=XGBClassifier()

In [ ]:
estimators=[('xgb',xgb)]

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
pipe=Pipeline(steps=estimators)

In [ ]:
pipe

In [ ]:
!pip install scikit_optimize

In [ ]:
from skopt import BayesSearchCV

In [ ]:
from skopt.space import Real,Categorical,Integer

In [ ]:
search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

In [ ]:
opt=BayesSearchCV(pipe,search_space,n_iter=10,cv=3,scoring='roc_auc',random_state=8)

In [ ]:
opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=3
)

In [55]:
opt.fit(X_train,Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13], got [ 0  1  2  3  4  5  6  7  9 10 11 12 13 14]