<a href="https://colab.research.google.com/github/OmegaS48/Internship_NITP/blob/main/Intern_Day14_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pickle

In [7]:
from sklearn.svm import SVC

In [9]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows',None);
pd.set_option('display.max_columns',None)
train=pd.concat([pd.read_csv('SDNFlow_Dataset_Normal.csv'),pd.read_csv('SDNFlow_Dataset_attack.csv')])
train=train.drop(columns=['ip_proto','src_port','dst_port','flow_ID','eth_type','ipv4_src','ipv4_dst','TnBPDstIP','TnPPDstIP','TnBPSrcIP','TnPPSrcIP','TnPPerDport','Tn_FlowsPDstIP','Tn_FlowsPSrcIP'])
train.head()

,flow_duration,tot_len_pkts,tot_pkts,flow_byts_s,flow_pkts_s,pkt_size_average,fwd_header_len,Byts_max_interval_2s,Byts_min_interval_2s,Byts_mean_interval_2s,Byts_std_interval_2s,Pkts_max_interval_2s,Pkts_mean_interval_2s,Pkts_min_interval_2s,Pkts_std_interval_2s,active_max,active_mean,active_min,active_std,idle_max,idle_mean,idle_min,idle_std,Attack,Category
0,6.472,113472.0,628.0,17532.756490,97.033375,180.687898,12560.0,112694.0,0.0,28368.00000,48686.674830,625.0,157.000000,0.0,270.202702,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,0.0,SSH
1,6.465,24492.0,370.0,3788.399072,57.231245,66.194595,7400.0,24294.0,0.0,6123.00000,10491.343150,367.0,92.500000,0.0,158.487381,2.0,2.0,2.0,0.0,5.0,5.0,5.0,0.0,0.0,SSH
2,4.798,2211.0,4.0,460.817007,0.833681,552.750000,32.0,1180.0,0.0,737.00000,524.675773,2.0,1.333333,0.0,0.942809,4.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,ICMP
3,595.270,10827817.0,25627.0,18189.757590,43.051052,422.515979,205016.0,44867.0,11454.0,36334.95638,2870.840349,103.0,85.996644,22.0,4.407512,596.0,596.0,596.0,0.0,0.0,0.0,0.0,0.0,0.0,STREAMING
4,595.251,154551644.0,114704.0,259641.132900,192.698542,1347.395418,917632.0,935885.0,32828.0,518629.67790,121204.950600,673.0,384.912752,29.0,84.666811,596.0,596.0,596.0,0.0,0.0,0.0,0.0,0.0,0.0,STREAMING

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
train['Category']=le.fit_transform(train['Category'])
train['Category'].value_counts()

Category
2    164974
8     84667
7     74644
0     53551
6      1487
5      1133
3       305
1        91
4        23
9         1
Name: count, dtype: int64

In [11]:
Y=train['Category']
X=train

In [12]:
X=X.drop(columns='Category')
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
from xgboost import XGBClassifier


xgb=XGBClassifier()


estimators=[('xgb',xgb)]


from sklearn.pipeline import Pipeline


pipe=Pipeline(steps=estimators)


pipe

Pipeline(steps=[('xgb',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [13]:
pip install scikit-optimize

Collecting scikit-optimize
  Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.5.3)
Collecting pyaml>=16.9 (from scikit-optimize)
  Downloading pyaml-26.2.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (2.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.16.3)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (1.6.1)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from scikit-optimize) (26.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.6.0)
Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 3.7 MB/s eta 0:00:00
Downloading pyaml-26.2.1-py3-none-any.whl (27 kB)
Installing collected packages: pyaml, scikit-optimize
Successfully installed pyaml-26.2.1 scikit-optimize-0.10.2

In [14]:
from skopt import BayesSearchCV


from skopt.space import Real,Categorical,Integer


search_space = {
    'max_depth': Integer(3, 8),
    'learning_rate': Real(0.01, 0.3, prior='log-uniform'),
    'n_estimators': Integer(100, 500),
    'subsample': Real(0.6, 1.0),
    'colsample_bytree': Real(0.6, 1.0),
    'reg_alpha': Real(0.0, 5.0),
    'reg_lambda': Real(0.1, 5.0),
    'gamma': Real(0.0, 5.0)
}

opt=BayesSearchCV(pipe,search_space,n_iter=10,cv=3,scoring='roc_auc',random_state=8)


opt = BayesSearchCV(
    xgb,
    search_spaces=search_space,
    n_iter=10,
    cv=3
)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
from xgboost import XGBClassifier

In [21]:
import torch
import torch.nn as nn

In [22]:
class TabTransformer(nn.Module):
    def __init__(
        self,
        input_dim,
        num_classes,
        embed_dim=32,
        num_heads=4,
        num_layers=2,
        dropout=0.2
    ):
        super(TabTransformer, self).__init__()

        # Feature embedding
        self.embedding = nn.Linear(input_dim, embed_dim)

        # Transformer Encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=num_heads,
            dropout=dropout,
            batch_first=True
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        # Classification head
        self.classifier = nn.Sequential(
            nn.Linear(embed_dim, 64),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(64, num_classes)
        )

    def forward(self, x):

        # Embed features
        x = self.embedding(x)

        # Add sequence dimension
        x = x.unsqueeze(1)

        # Transformer
        x = self.transformer(x)

        # Pooling
        x = x.mean(dim=1)

        # Classification
        x = self.classifier(x)

        return x

In [23]:
model = TabTransformer(
    input_dim=X_train.shape[1],
    num_classes=len(set(Y_train)),
    embed_dim=32,
    num_heads=4,
    num_layers=2
)

In [24]:
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [25]:
from torch.utils.data import Dataset, DataLoader

In [39]:
class TabDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X.to_numpy(), dtype=torch.float32)
        self.y = torch.tensor(Y.to_numpy(), dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_dataset = TabDataset(X_train, Y_train)
test_dataset = TabDataset(X_test, Y_test)

train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=256)

In [40]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = TabTransformer(
    input_dim=X_train.shape[1],
    num_classes=len(np.unique(Y))
).to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [41]:
epochs = 20

for epoch in range(epochs):

    model.train()
    total_loss = 0

    for batch_X, batch_y in train_loader:

        batch_X = batch_X.to(device)
        batch_y = batch_y.to(device)

        optimizer.zero_grad()

        outputs = model(batch_X)

        loss = criterion(outputs, batch_y)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss:.4f}")

Epoch 1/20, Loss: 1381.7817
Epoch 2/20, Loss: 1361.3405
Epoch 3/20, Loss: 1360.2132
Epoch 4/20, Loss: 1360.4399
Epoch 5/20, Loss: 1359.8921
Epoch 6/20, Loss: 1359.6588
Epoch 7/20, Loss: 1358.9840
Epoch 8/20, Loss: 1358.8790
Epoch 9/20, Loss: 1358.9239
Epoch 10/20, Loss: 1358.7932
Epoch 11/20, Loss: 1358.5573
Epoch 12/20, Loss: 1358.5363
Epoch 13/20, Loss: 1358.4683
Epoch 14/20, Loss: 1358.3438
Epoch 15/20, Loss: 1358.0764
Epoch 16/20, Loss: 1357.8563
Epoch 17/20, Loss: 1357.8599
Epoch 18/20, Loss: 1357.8315
Epoch 19/20, Loss: 1357.7156
Epoch 20/20, Loss: 1357.8045

In [42]:
model.eval()

predictions = []
actuals = []

with torch.no_grad():

    for batch_X, batch_y in test_loader:

        batch_X = batch_X.to(device)

        outputs = model(batch_X)

        preds = torch.argmax(outputs, dim=1)

        predictions.extend(preds.cpu().numpy())
        actuals.extend(batch_y.numpy())

In [43]:
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [44]:
from sklearn.preprocessing import LabelEncoder

In [46]:
accuracy = accuracy_score(actuals, predictions)

print("\nAccuracy:", accuracy)

print("\nClassification Report:\n")
print(
    classification_report(
        actuals,
        predictions
    )
)

print("\nConfusion Matrix:\n")
print(
    confusion_matrix(
        actuals,
        predictions
    )
)

Accuracy: 0.772500525099769

Classification Report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00     16770
           2       0.77      1.00      0.87     58847
           3       0.00      0.00      0.00        66
           5       0.00      0.00      0.00       204
           6       0.00      0.00      0.00       289

    accuracy                           0.77     76176
   macro avg       0.15      0.20      0.17     76176
weighted avg       0.60      0.77      0.67     76176


Confusion Matrix:

[[    0 16770     0     0     0]
 [    1 58846     0     0     0]
 [    0    66     0     0     0]
 [    0   204     0     0     0]
 [    0   289     0     0     0]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [47]:
from sklearn.ensemble import HistGradientBoostingClassifier

In [48]:
models=[LogisticRegression(),SVC(kernel='linear'),KNeighborsClassifier(),RandomForestClassifier(),HistGradientBoostingClassifier(),XGBClassifier()]

In [49]:
def compare():
  for model in models:
    model.fit(X_train,Y_train)
    test_predict=model.predict(X_test)
    accuracy_score(Y_test,test_predict)
    print(model)
    print(accuracy_score(Y_test,test_predict))

In [53]:
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# fill missing values with column mean
imputer = SimpleImputer(strategy='median')

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [ ]:
compare()

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()
0.429413463558076